version: '3.8'
services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  jobmaster:
    container_name: jobmaster_service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    ports:
      - "3001:3001"
    depends_on:
      - redis
    command: node jobmaster/server.js

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: node worker/processor.js

networks:
  default:
    external:
      name: shared-network

